### ISSUE TITLE
RunTime Exception

### ISSUE THREAD

**Issue by rajath** [andreszs/cordova-plugin-sms-retriever#9]
Hi,
We are seeing a runtime exception when we use the plugin, resulting in the app crashing. This doesn't happen all the time but is affecting all models. Here is the error trace from firebase:

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.cordova.OTPAutoVerification.OTPAutoVerification$Common$OTPListener.onOTPTimeOut()' on a null object reference
       at org.apache.cordova.OTPAutoVerification.OTPAutoVerification$SMSListener.onReceive(OTPAutoVerification.java:182)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4443)
       at android.app.ActivityThread.access$1600(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2159)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by rajath** [comment]
Sorry, this is connected to a different plugin
